### PR TITLE
Add simple metric tracking

### PR DESCRIPTION
**Pull request by AmanDaVinci**
Added simple metric tracking to a CSV file. Let me know if the metrics tracked now are sufficient.

### CODE REVIEW

**Review by VaniOFX — COMMENTED** [review]
Should we also keep track of the tuple (state, next_state, reward, action, done)?

**Comment by AmanDaVinci** [comment]
Yeah, it could be useful. Let's put it in a separate record file ordered by time?

**Comment by VaniOFX** [comment]
Sounds good. If you have multiple experiments with the same parameters, do the results get overwritten?

**Comment by AmanDaVinci** [comment]
> Should we also keep track of the tuple (state, next_state, reward, action, done)?

done.

**Comment by AmanDaVinci** [comment]
> Sounds good. If you have multiple experiments with the same parameters, do the results get overwritten?

The logs are appended, so the old logs are still available. But the exp_records.csv and interactions.csv are overwritten, so only recent ones are available.

**Comment by VaniOFX** [comment]
> > Sounds good. If you have multiple experiments with the same parameters, do the results get overwritten?
> 
> The logs are appended, so the old logs are still available. But the exp_records.csv and interactions.csv are overwritten, so only recent ones are available.

What else does hydra log?

**Comment by AmanDaVinci** [comment]
Its a subset of what is in exp_records.csv, just to see how the training is going. It specifically logs average steps as score, max Q and epsilon.

**Review by VaniOFX — APPROVED** [review]

**Pull request merged**
